### ISSUE TITLE
Error at Xposed (API Problem)

### ISSUE THREAD

**Issue by vinanrra** [leewp14/xposed.leewp14.NEClient#3]
10-10 02:07:19.914 I/Xposed  ( 8591): detail api failed 17639686
10-10 02:07:19.918 E/Xposed  ( 8591): org.json.JSONException: No value for songs
10-10 02:07:19.918 E/Xposed  ( 8591): 	at org.json.JSONObject.get(JSONObject.java:389)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at org.json.JSONObject.getJSONArray(JSONObject.java:584)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at xposed.leewp14.NEClient.b$a.<init>(Unknown Source)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at xposed.leewp14.NEClient.b.b(Unknown Source)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at xposed.leewp14.NEClient.b.a(Unknown Source)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at xposed.leewp14.NEClient.Main$1$1.afterHookedMethod(Unknown Source)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:351)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at com.netease.cloudmusic.i.b.a(<Xposed>)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at com.netease.cloudmusic.utils.x.h(ProGuard:468)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at com.netease.cloudmusic.c.a.a.b(ProGuard:12750)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at java.lang.reflect.Method.invoke(Native Method)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at com.netease.cloudmusic.utils.b.invoke(ProGuard:54)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at $Proxy0.b(Unknown Source)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at com.netease.cloudmusic.module.transfer.download.d.h(ProGuard:285)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at com.netease.cloudmusic.module.transfer.download.d.b(ProGuard:119)
10-10 02:07:19.918 E/Xposed  ( 8591): 	at com.netease.cloudmusic.module.transfer.a.d$d.run(ProGuard:302)

**Comment by leewp14** [comment]
Can provide more details? (Ie android version, netease version, module version, xposed version)

**Comment by vinanrra** [comment]
Yes sorry i was on phone here is full log of today and yesterday:

https://docs.google.com/document/d/1FwAz0wSM14ZvR5yThoWptWLHHbUDYUMrbbdKFmlHJbQ/edit?usp=sharing

Device: 
Redmi Note 4 (Xiaomi), Android version 7.1.2 (SDK 25)

ROM: 
lineage_mido-userdebug 7.1.2 NJH47F 29cc007710

Xposed version: 
88.0 (Systemless by topjohnwu), compiled for SDK 25

**Comment by leewp14** [comment]
This error is due to recent NetEase API changes. We will need to wait the original developer of this module (bin456789) to make changes to his code. 
But some songs seems to be able to play on my phone. Did you enable overseas mode? If yes, try to turn it off. 
I tried Whole Lotta Love which the log file indicates, and I can play it without any problem. 
For ref, my configuration is Samsung N7000, RROS 5.8.5, Xposed Official v88, SELinux Permissive, NetEase Music v4.2.0.788545

**Comment by leewp14** [comment]
Original developer updated his module. Will not update mine anymore.
