### ISSUE TITLE
每日推荐获取为空

### ISSUE THREAD

**Issue by tl0rty2q** [leewp14/xposed.leewp14.NEClient#5]
每日推荐歌曲无法获取。

**Comment by leewp14** [comment]
我这儿没问题。能否附上截图？

**Comment by renzhe2007** [comment]
同上 每日推荐和私人FM无法使用。
![image](https://user-images.githubusercontent.com/33191275/32140776-0c79b7e8-bc43-11e7-89dc-892d57edfcbb.png)
![image](https://user-images.githubusercontent.com/33191275/32140779-188ba618-bc43-11e7-92a1-9ef848d30608.png)
非常感谢这么有用的插件。

**Comment by leewp14** [comment]
但我这真的没问题哦。。
能查看xposed log是否有error？
也请回复一下是否有开启海外模式。谢谢。

![img_20171030_211102](https://user-images.githubusercontent.com/17796518/32172690-74144a2e-bdb7-11e7-8fd5-0ad160df356d.jpg)
![img_20171030_211049](https://user-images.githubusercontent.com/17796518/32172691-7461774a-bdb7-11e7-9dba-f89d1d3d34df.jpg)
