### ISSUE TITLE
已经失效，不能听资源不存在的歌曲了，求更新

### ISSUE THREAD

**Issue by jczai** [leewp14/xposed.leewp14.NEClient#7]

**Comment by jczai** [comment]
发现4.0的网易云还可以用，蟹蟹大佬

**Comment by jczai** [comment]
发现4.0的网易云还可以用，谢谢大佬

**Comment by ghost** [comment]
最后可用的云音乐版本是4.2.1，以上

**Comment by leewp14** [comment]
此项目不再更新了，建议使用原作者的最新方块。谢谢！
https://github.com/bin456789/Unblock163MusicClient-Xposed
